name: Leet_Stat

on: 
  push:
    branches:
    - main
  schedule:
    - cron: '0 */24 * * *'
  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Configure pip cache
      uses: actions/cache@v2.1.4
      id: pip-cache
      with:
        # path: ~/.cache/pip
        # key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ env.pythonLocation }}-
    
    - name: Install dependencies
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get LeetCode Data
      run: python leet/leet_stat.py ${{ secrets.LEETCODE_EMAIL }} ${{ secrets.LEETCODE_PASSWORD }}

    - name: commit
      run: |
        git config --global user.email home@xuzhiwei.site
        git config --global user.name xzw
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
      
  
#       - name: Add conda to system path
#       run: |
#         # $CONDA is an environment variable pointing to the root of the miniconda directory
#         echo $CONDA/bin >> $GITHUB_PATH
    
#     - name: Install dependencies
#       run: |
#         conda env update --file environment.yml --name base
    
#     - name: Lint with flake8
#       run: |
#         conda install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
#     - name: Test with pytest
#       run: |
#         conda install pytest
#         pytest
